### ISSUE TITLE
Installed it 

### ISSUE THREAD

**Issue by designMoreWeb** [NickTikhonov/hyperline#51]
So i  installed hyperline and added the configurations to the .hyper.js file and reloaded the hyper application using > cmd+shift+r.  However this is not working for me and i can't see anything in my terminal how do i fix this please help me. 
<img width="1242" alt="screen shot 2016-10-27 at 6 38 59 pm" src="https://cloud.githubusercontent.com/assets/5986856/19788148/c646392a-9c74-11e6-9479-52a21d139d06.png">

**Comment by Arttse** [comment]
Same in #52 

Using hyperline version `0.6.0` fast fix is the using steps from readme [contributing](https://github.com/NickTikhonov/hyperline#contributing). In step 3 run only `npm run build`.

Now just have to wait until a new version of the fix will be published.

**Comment by designMoreWeb** [comment]
I did that and now i am getting this error
<img width="1280" alt="screen shot 2016-10-27 at 8 03 13 pm" src="https://cloud.githubusercontent.com/assets/5986856/19789764/702fee44-9c80-11e6-9874-d457c424689a.png">

**Comment by Arttse** [comment]
@designMoreWeb you have not fulfilled all the steps from [readme contributing](https://github.com/NickTikhonov/hyperline#contributing). Do you know how to clone git repos and install NPM modules?

In terminal:
```sh
# Step 1
git clone https://github.com/NickTikhonov/hyperline.git ~/.hyper_plugins/local/hyperline

# Step 2
cd ~/.hyper_plugins/local/hyperline
npm install

# Step 3
npm run build
```

Step 4:
Add the name `hyperline` to localPlugins in `~/.hyper.js`. Make sure `hyperline` is removed from plugins in `~/.hyper.js`. You should get something like this:
```js
module.exports = {

  config: {/* ... */},

  plugins: [],

  localPlugins: ["hyperline"]
};
```

Step 5:
Reload terminal window

**Comment by designMoreWeb** [comment]
alright so i performed npm install and it worked. However when i am running npm run build in the directory i get 
<img width="1266" alt="screen shot 2016-10-27 at 8 28 12 pm" src="https://cloud.githubusercontent.com/assets/5986856/19790149/e856bc74-9c83-11e6-8bbf-7cc14f4cab9e.png">

**Comment by Arttse** [comment]
Amazing. It seems that webpack not found the right file. I feel like not everything was cloned. Try `tree ./src` in current folder. My tree:
```sh
~/.hyper_plugins/local/hyperline/src
├── index.js
└── lib
    ├── core
    │   ├── hyperline.js
    │   └── PluginWrapper.js
    ├── plugins
    │   ├── battery.js
    │   ├── cpu.js
    │   ├── hostname.js
    │   ├── index.js
    │   ├── memory.js
    │   ├── network.js
    │   └── uptime.js
    └── utils
        ├── colors.js
        ├── config.js
        └── icons.js

4 directories, 13 files
```

**Comment by designMoreWeb** [comment]
doesnt work for me as tree command is not found on my mac nor i can install it  for a weird reason

**Comment by timneutkens** [comment]
@Arttse thanks for picking up support 😉
@designMoreWeb you are totally right. Will do a new release soon 👍

**Comment by timneutkens** [comment]
Since #52 is more complete i'm closing this one.
