### ISSUE TITLE
Not showing up on Linux Ubuntu 16.04

### ISSUE THREAD

**Issue by Arttse** [NickTikhonov/hyperline#52]
Using default `.hyper.js` file.

I tried different methods:
- Just add "hyperline" to plugins to `.hyper.js` file.
- Install by `hpm` — `hpm i hyperline`.
- Install to local by `hpm` — `hpm f hyperline`.

Nothing to show `hyperline`. Maybe I something doing wrong?
## 

Node.js 6.9.1
NPM 3.10.8

Hyper 0.8.3
hpm-cli 1.4.0
hyperline 0.6.0

Linux Ubuntu 16.04
Linux kernel 4.4.0-45-generic

**Comment by Arttse** [comment]
As it turned out, the problem was that you published version `0.6.0`, forgetting to run the command `npm run build`.

Now in version hyperline `0.6.0` in `dist/hyperline.js` is this code:
```js
exports.mapHyperTermState = mapHyperTermState;
exports.decorateHyperTerm = decorateHyperTerm;
```

And if I take the source code and run `npm run build`, i see in `dist/hyperline.js` is this code:
```js
exports.mapHyperState = mapHyperState;
exports.decorateTerm = decorateTerm;
```

Now problem is solved. Now the `hyperline` shows.

Please publish the new version with fix.

**Comment by timneutkens** [comment]
Contacting Nick already 😉

**Comment by JorgeGonzalez** [comment]
Same issue on macOS Sierra.

**Comment by timneutkens** [comment]
@NickTikhonov

**Comment by taylorthurlow** [comment]
Same issue on El Capitan as well.

**Comment by timneutkens** [comment]
Just contacted Nick, he's going to do a new release 👍

**Comment by timneutkens** [comment]
New release (0.6.1) was just released. Go download :shipit: 🚀

**Comment by taylorthurlow** [comment]
Working great, thanks for the quick response.

**Comment by timneutkens** [comment]
@taylorthurlow great 👍
