### ISSUE TITLE
Uncorrect display memory

### ISSUE THREAD

**Issue by Arttse** [NickTikhonov/hyperline#53]
In system monitor:
![system-monitor_memory](https://cloud.githubusercontent.com/assets/7123950/19790797/256da5d8-9cc4-11e6-9884-c069a0ae31a6.png)

In htop:
![htop_memory](https://cloud.githubusercontent.com/assets/7123950/19790968/b03cb7f2-9cc5-11e6-97b4-a0b0e0c6fe4e.png)

In hyperline:
![hyperline_memory](https://cloud.githubusercontent.com/assets/7123950/19790975/bf6e5f46-9cc5-11e6-98d8-5ebe2724c88a.png)

Whats going on? :cold_sweat:
## 

Linux Ubuntu 16.04.
hyperline 0.6.0

**Comment by timneutkens** [comment]
Noticed this too (me being on mac). It is taken from os.freeMem (core node.js function).
There seem to be more reports of it being incorrect:
https://groups.google.com/forum/#!topic/nodejs/R1mJgyqzaTY
https://github.com/Unitech/keymetrics.io/issues/24

**Comment by Arttse** [comment]
You have dependency is `systeminformation`. I checked, it seems this module correctly displays the memory. You can use the [mem](https://github.com/sebhildebrandt/systeminformation/blob/master/lib/index.js#L772) function to get correct memory.

And another thing, can show the usual `active / total` memory? Or is it better just to make a custom show `active` or `available` memory, in config in `.hyper.js`.

**Comment by timneutkens** [comment]
@Arttse feel free to PR it 😄 any help is welcome.

**Comment by Arttse** [comment]
@timneutkens thank you. I think we should wait, when #40 is merged.

**Comment by timneutkens** [comment]
@arttse That one will be open for a while. I'm doing a total rework of the core code again to implement classes instead of inline styling.

**Comment by Arttse** [comment]
@timneutkens I already did it for me. It worked, but looks ugly and without settings. If you want, I can create PR with these changes.

**Comment by timneutkens** [comment]
That's ok 👍
