### ISSUE TITLE
Add user to hostname plugin

### ISSUE THREAD

**Issue by hellominotaur** [NickTikhonov/hyperline#60]
I wrote this before for the plugins but didn't get a reply from the maintainer, so thought it would make far more sense as an explicit feature request.

In my fork of hyperline the hostname plugin is displayed in the format ```user@hostname```. There's an option to switch the username on or off, with off as default.

If you think that's what other people might be interested in using I can swing a PR over.

**Comment by timneutkens** [comment]
Sure, do create the pr 👍
