### ISSUE TITLE
Rendering Issues in Vim

### ISSUE THREAD

**Issue by tamoore** [NickTikhonov/hyperline#63]
I've come across some column rendering issues in vim 8.0 on macOS Sierra.
This was in a `tmux` session, but it also occurs outside the session. You can see the 80 col ruler is misaligned 3/4 page down.

Thanks for hyper, it's an awesome app. Enjoying playing with it.

<img width="1440" alt="screen shot 2016-12-13 at 8 43 52 pm" src="https://cloud.githubusercontent.com/assets/11851685/21135149/e6976bc0-c174-11e6-8551-f68957a22605.png">

**Comment by timneutkens** [comment]
@tamoore think you have to add this issue to https://www.github.com/zeit/hyper. This is the hyperline repository 👍

**Comment by tamoore** [comment]
Ha! Sorry! Too many tabs!

**Comment by timneutkens** [comment]
👍
