### ISSUE TITLE
Allow creating plugins as separate npm packages

### ISSUE THREAD

**Issue by dotterian** [NickTikhonov/hyperline#64]
I'm pretty new in js and react development, so I may be confusing something, but it seems to me that for now so called "plugins" can be defined only in `src/lib/plugins` and thus can't be called "plugins" at all. It's just internal modules of hyperline plugin.
It would be great to have an option to create plugin as separate npm package and define it in hyperline config like:
```js
{
  "hyperline": {
    "plugins": [
      // ...
      {
        "name": "my-plugin-package-name",
        "options": {
          // ...
        }
      }
    ]
  }
}
```

**Comment by timneutkens** [comment]
Please see https://github.com/NickTikhonov/hyperline/issues/41
