### ISSUE TITLE
Hyperline makes switching between tabs really slow

### ISSUE THREAD

**Issue by gholtslander-va** [NickTikhonov/hyperline#65]
I think this is because whenever I switch between the tabs, Hyperline recalculates all of the values such as RAM being used (and how much there is, for that matter) so that it can display itself.

I had to remove the extension. But maybe instead I'll try and hack on a fix for it.

**Comment by timneutkens** [comment]
Hmm I'll check it out. Currently rewriting hyperline. So if you could Wait for that <3

**Comment by gholtslander-va** [comment]
Sounds good, and I'll hold off on any further investigations for now 😄
